language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverageclover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverageclover
